//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class pogodakKrila : MonoBehaviour
{
	public GameObject explosionPrefab;
	private bool isDone = false;

	void OnTriggerEnter(Collider other){
		//if (other.gameObject.tag.Equals("PlayerCollider")){
		if (!isDone) {	

			GameObject parent = transform.parent.gameObject;
			
			GameObject explosion = (GameObject)Instantiate (explosionPrefab, parent.transform.TransformPoint (Vector3.zero), transform.rotation);
			Destroy (explosion, 2);

			GameObject child = parent.transform.GetChild (0).gameObject;
			child.AddComponent<Rigidbody> (); // Add the rigidbody.
			child.GetComponent<Rigidbody> ().mass = 1;
			child.GetComponent<Rigidbody> ().AddForce (new Vector3 (100, 100, 100));
			
			child = parent.transform.GetChild (1).gameObject;
			child.AddComponent<Rigidbody> (); // Add the rigidbody.
			child.GetComponent<Rigidbody> ().mass = 1;
			child.GetComponent<Rigidbody> ().AddForce (new Vector3 (-100, -100, -100));                             
			//}
			isDone = true;
		}
	}
	public pogodakKrila ()
	{
	}


}


